

POST http://localhost/v2-doardigital/api/atualizar-adm
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "nome": "Bruno Vieira",
    "telefone": "(82) 9 9977-6698",
    "cpf": "136546",
    "token": "eyJzZWNyZXQiOiIgNjFhNjY2N2E4NGFmYyIsIm5vbWUiOiJyYWZhZWwiLCJlbWFpbCI6InJhZmFlbEBnbWFpbC5jb20iLCJzdXBlcl9hZG0iOiIwIiwic3RlcCI6IjEifQ==.4659492ae33cb9ca6889fdee955a4ee0b57c5330"
}

###

GET http://localhost/v2-doardigital/api/credencial

{
    "id": 2
}

###

POST http://localhost/v2-doardigital/api/step-update

{
    "step": 2,
    "token" : ""
}

###
GET http://doardigital.com.br/api/list-endereco
{
    "token": ""
}

### 
GET http://doardigital.com.br/api/list-subadm

{
    "token": "eyJzZWNyZXQiOiIgNjFiNzQ3N2RkOWVmNCIsIm5vbWUiOiJnaWxkZXRlIiwiZW1haWwiOiJnaWxkZXRlQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.d6024749fac75479d40db1611f9555c66c48ab67"
}

###
POST http://doardigital.com.br/api/criate-subadm
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "token": "eyJzZWNyZXQiOiIgNjFiNzQ3N2RkOWVmNCIsIm5vbWUiOiJnaWxkZXRlIiwiZW1haWwiOiJnaWxkZXRlQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.d6024749fac75479d40db1611f9555c66c48ab67",
    "nome" : "Bruno",
    "senha": "123123",
    "telefone": "123123",
    "credencial_id" : "12"
}

###
POST http://doardigital.com.br/api/atualizar-subadm
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "token": "eyJzZWNyZXQiOiIgNjFiNzQ3N2RkOWVmNCIsIm5vbWUiOiJnaWxkZXRlIiwiZW1haWwiOiJnaWxkZXRlQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.d6024749fac75479d40db1611f9555c66c48ab67",
    "nome" : "Bruno",
    "telefone": "123123",
    "credencial_id" : "12",
    "secret" : ""
}






//ENDERECO



###
POST http://localhost/v2-doardigital/api/endereco-instituicao
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "token": "eyJzZWNyZXQiOiIgNjFhNjY2N2E4NGFmYyIsIm5vbWUiOiJyYWZhZWwiLCJlbWFpbCI6InJhZmFlbEBnbWFpbC5jb20iLCJzdXBlcl9hZG0iOiIwIiwic3RlcCI6IjEifQ==.4659492ae33cb9ca6889fdee955a4ee0b57c5330",
    "id": "5",
    "nome_identificacao" : "casa",
    "cep" : "(028.35,090)",
    "logradouro" : "rua cardoso",
    "numero" : "76",
    "complemento" : "AP",
    "bairro" : "montes claros",
    "cidade" : "brasilandia",
    "estado" : "MG"

}

###
POST http://localhost/v2-doardigital/api/create-endereco
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "token": "eyJzZWNyZXQiOiIgNjFhNjY2N2E4NGFmYyIsIm5vbWUiOiJyYWZhZWwiLCJlbWFpbCI6InJhZmFlbEBnbWFpbC5jb20iLCJzdXBlcl9hZG0iOiIwIiwic3RlcCI6IjEifQ==.4659492ae33cb9ca6889fdee955a4ee0b57c5330",
    "nome_identificacao" : "casa",
    "cep" : "(028.35,090)",
    "logradouro" : "rua cardoso",
    "numero" : "76",
    "complemento" : "AP",
    "bairro" : "montes claros",
    "cidade" : "brasilandia",
    "estado" : "MG"
}

###
POST http://localhost/v2-doardigital/api/update-endereco
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "nome_identificacao" : "casa",
    "cep" : "(028.35,090)",
    "logradouro" : "rua cardoso",
    "numero" : "76",
    "complemento" : "AP",
    "bairro" : "montes claros",
    "cidade" : "brasilandia",
    "estado" : "MG"
}

###
POST http://localhost/v2-doardigital/api/update-endereco
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    
}

###
POST http://localhost/v2-doardigital/api/endereco
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "token": "eyJzZWNyZXQiOiIgNjFhNjY2N2E4NGFmYyIsIm5vbWUiOiJyYWZhZWwiLCJlbWFpbCI6InJhZmFlbEBnbWFpbC5jb20iLCJzdXBlcl9hZG0iOiIwIiwic3RlcCI6IjEifQ==.4659492ae33cb9ca6889fdee955a4ee0b57c5330",
    "secret": 
}

###
POST http://localhost/v2-doardigital/api/delete-endereco
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "token": "eyJzZWNyZXQiOiIgNjFhNjY2N2E4NGFmYyIsIm5vbWUiOiJyYWZhZWwiLCJlbWFpbCI6InJhZmFlbEBnbWFpbC5jb20iLCJzdXBlcl9hZG0iOiIwIiwic3RlcCI6IjEifQ==.4659492ae33cb9ca6889fdee955a4ee0b57c5330",
    "secret": 
}

POST http://localhost/v2-doardigital/api/list-endereco
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    
}


//DOADOR

###

POST http://localhost/v2-doardigital/api/list-doador
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "cpf": 
}

###
POST http://localhost/v2-doardigital/api/doador
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{

}

###

POST http://localhost/v2-doardigital/api/create-doador
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{

}



// TRANSACAO


###
POST http://localhost/v2-doardigital/api/transacao
Content-Type: application/x-www-form-urlencoded

token= eyJzZWNyZXQiOiIgNjFiNzQ3N2RkOWVmNCIsIm5vbWUiOiJnaWxkZXRlIiwiZW1haWwiOiJnaWxkZXRlQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.d6024749fac75479d40db1611f9555c66c48ab67
&instituicao_id= 5
&mensal= 1
&planos_id= 13
&planos_valor= 1000
&email= victorfernando@gmail.com
&nome= victor fernando
&genero= masculino
&cpf= 123.123.123-12
&telefone= (38) 9 9801-9210
&cep= 02835-090
&numero= 75 b
&estado= SP
&endereco= rua plinio
&bairro= Serralheiro
&cidade= Sao paulo
&type_pagamento= cartao
&cart_numero= 4568 4568 4568 4568
&cart_cvv= 0055
&cart_validade= 12/21
&cart_nome= victor fernando


