POST https://doardigital.tk/api/transacao
Content-Type: application/x-www-form-urlencoded

instituicao_id=int
&planos_id=int
&planos_nome=string
&planos_valor=int
&mensal=[0,1]
&nome=string
&cpf=string
&telefone=string
&email=string
&data_nascimento=string
&cep=string
&numero=string
&estado=string
&endereco=string
&bairro=string
&cidade=string
&complemento=string
&type_pagamento=[credit_card, pix, boleto]
&cart_numero=int
&cart_cvv=int
&cart_validade=string

###
GET https://doardigital.tk/api/list-doacoes?instituicao_id=int
Content-Type: application/x-www-form-urlencoded