POST http://localhost/v2-doardigital/api/save-evendas
Content-Type: application/x-www-form-urlencoded

instituicao_id=5,
&canal=5

###
GET http://localhost/v2-doardigital/api/list-evendas?instituicao_id=5
Content-Type: application/x-www-form-urlencoded