
GET http://doardigital.tk/api/list-metas

###
GET http://doardigital.tk/api/instituicao?
token=eyJzZWNyZXQiOiIgNjFiNzQ3N2RkOWVmNCIsIm5vbWUiOiJnaWxkZXRlIiwiZW1haWwiOiJnaWxkZXRlQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.d6024749fac75479d40db1611f9555c66c48ab67

###

GET http://localhost/v2-doardigital/api/instituicao-id?instituicao_id=5

###

POST http://localhost/v2-doardigital/api/update-instituicao
Content-Type: application/x-www-form-urlencoded

token=eyJzZWNyZXQiOiIgNjFkYjU1M2I4ODNjMiIsIm5vbWUiOiJqb2FxdWltIE1pZ3VlbCIsImVtYWlsIjoiam9hcXVpbUBnbWFpbC5jb20iLCJzdXBlcl9hZG0iOiIwIiwic3RlcCI6IjEifQ==.edb1a7efadc35fa936991c29e23cb34ea8d9ed8e,
&instituicao_id=8,
&nome_fantasia= empresa,
&razao_social=exemplo,
&email=ezemplo@gmail.com,
&cnpj=123.456.789.31/2.12,
&telefone=2123-3344

###

POST http://localhost/v2-doardigital/api/on_off
Content-Type: application/x-www-form-urlencoded

token=eyJzZWNyZXQiOiIgNjFiNzQ3N2RkOWVmNCIsIm5vbWUiOiJnaWxkZXRlIiwiZW1haWwiOiJnaWxkZXRlQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.d6024749fac75479d40db1611f9555c66c48ab67
&instituicao_id=5

###
POST http://localhost/v2-doardigital/api/create-instituicao
Content-Type: application/x-www-form-urlencoded

token=eyJzZWNyZXQiOiIgNjFiNzQ3N2RkOWVmNCIsIm5vbWUiOiJnaWxkZXRlIiwiZW1haWwiOiJnaWxkZXRlQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.d6024749fac75479d40db1611f9555c66c48ab67
&nome_fantasia=empresa,
&sub_domain=teste,
&razao_social=exemplo,
&email=ezemplo@gmail.com,
&cnpj=123.456.789.31/2.12,
&telefone=2123-3345

###
POST http://localhost/v2-doardigital/api/update-domain-person
Content-Type: application/x-www-form-urlencoded

token=eyJzZWNyZXQiOiIgNjFiNzQ3N2RkOWVmNCIsIm5vbWUiOiJnaWxkZXRlIiwiZW1haWwiOiJnaWxkZXRlQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.d6024749fac75479d40db1611f9555c66c48ab67,
&instituicao_id=5,
&dominio=exemplo.com

###
POST http://localhost/v2-doardigital/api/endereco-instituicao
Content-Type: application/x-www-form-urlencoded

id=4,
&nome_identificacao=vasio,
&logradouro=rua pedro,
&complemento=casa,
&bairro=brasil,
&cidade=SP,
&estado=SP,
&numero=33,
&cep=12332344

###
GET http://localhost/v2-doardigital/api/subdominio-disponivel?subdomain=teste
Content-Type: application/x-www-form-urlencoded
// criar ou salvar dados bancario 