###
POST http://localhost/v2-doardigital/api/login
Content-Type: application/x-www-form-urlencoded;

# email=br.rafael@outlook.com
# &senha=12345678

###
POST http://localhost/v2-doardigital/api/recuperar-senha
Content-Type: application/x-www-form-urlencoded;

email=br.rafael@outlook.com

###
GET http://localhost/v2-doardigital/api/validar?token=eyJzZWNyZXQiOiI2MTllNGY2MGNmNGYyIiwibm9tZSI6ImJydW5hbyBvIGZlcmluaGEgZGUgYWxhZ29hcyIsImVtYWlsIjoiYnIucmFmYWVsQG91dGxvb2suY29tIiwic3VwZXJfYWRtIjoiMSIsInN0ZXAiOiIxIiwiY3JlZGVuY2lhbCI6MH0=.84d79324a2c0b7a3a915a7927b3d315feb24c273

###
GET http://localhost/v2-doardigital/api/profile?token=eyJzZWNyZXQiOiIgNjFiNzQ3N2RkOWVmNCIsIm5vbWUiOiJnaWxkZXRlIiwiZW1haWwiOiJnaWxkZXRlQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.d6024749fac75479d40db1611f9555c66c48ab67"
