POST http://localhost/v2-doardigital/api/save-mailBoss
Content-Type: application/x-www-form-urlencoded

instituicao_id=5,
&token=dfs4
&token_uid=asdad3er3qwdrh0983uen

###
GET http://localhost/v2-doardigital/api/list-mailBoss?instituicao_id=5
Content-Type: application/x-www-form-urlencoded