POST http://localhost/v2-doardigital/api/create-plano
Content-Type: application/x-www-form-urlencoded

nome=plano 5
&instituicao_id=5
&amount=1000

###
GET http://localhost/v2-doardigital/api/list-plano
Content-Type: application/x-www-form-urlencoded


###
GET http://localhost/v2-doardigital/api/plano
Content-Type: application/x-www-form-urlencoded

instituicao_id=5

###
POST http://localhost/v2-doardigital/api/update-plano
Content-Type: application/x-www-form-urlencoded

id=1
&nome=Melhor do dia


###
POST http://localhost/v2-doardigital/api/on-off-plano
Content-Type: application/x-www-form-urlencoded

id=1