POST https://doardigital.com.br/api/smtp-save
Content-Type: application/x-www-form-urlencoded

token=string
&instituicao_id=int
&host=string
&protocolo=string
&porta=int
&email=string
&senha=strin

###
GET https://doardigital.com.br/api/list-smtp?instituicao_id=int
Content-Type: application/x-www-form-urlencoded