// criar 

// listar todos por ID do adm 

// desativar 

// pegar dados pelo ID

// atualizar




POST http://localhost/v2-doardigital/api/vinclular-sub-adm
Content-Type: application/x-www-form-urlencoded

token=eyJzZWNyZXQiOiIgNjFkYjU1M2I4ODNjMiIsIm5vbWUiOiJqb2FxdWltIE1pZ3VlbCIsImVtYWlsIjoiam9hcXVpbUBnbWFpbC5jb20iLCJzdXBlcl9hZG0iOiIwIiwic3RlcCI6IjEifQ==.edb1a7efadc35fa936991c29e23cb34ea8d9ed8e,
&instituicao_id=5
&sub_adm_id=1