POST http://localhost/v2-doardigital/api/criar-adm
Content-Type: multipart/form-data;

{
    "nome": "Bruno Vieira",
    "email": "br.rafael@outlook.com",
    "senha": "12312345",
    "telefone": "(82) 9 9977-6698"
}

###
POST http://localhost/v2-doardigital/api/login
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "email": "br.rafael@outlook.com",
    "senha": "12312345",
}

###
POST http://localhost/v2-doardigital/api/recuperar-senha
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "email": "br.rafael@outlook.com",
}

###
POST http://localhost/v2-doardigital/api/alterar-senha
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "senha": "123123",
    "token": ""
}

###
POST http://localhost/v2-doardigital/api/atualizar-adm
Content-Type: multipart/form-data; boundary=X-INSOMNIA-BOUNDARY

{
    "nome": "Bruno Vieira",
    "telefone": "(82) 9 9977-6698",
    "token": ""
}

###
GET http://localhost/v2-doardigital/api/gravatar?email=br.rafael@outlook.com

