@host=http://hostdoar.tk
@token=eyJjb2RlIjoiYWRtXzYyZDk3MzFhMTIwMzAifQ==.f28ebb285d23f0ff5b23270e73aeb13d2c6c2b80
@institution_fk=inst_62d990c744f00

POST https://14fpuojlqf.execute-api.us-east-1.amazonaws.com/prod/

###
POST https://r3nmn03mmk.execute-api.us-east-1.amazonaws.com/default/VerificarIdentidadeEmail 

{
    "EMAIL" : ""
}

###
POST https://cjylc0fag4.execute-api.us-east-1.amazonaws.com/default/ApagarIdentidadeEmail

{
    "EMAIL" : ""
}

###
POST {{host}}/api/aws/create-state-machine
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&institution_fk={{institution_fk}}5