@host=https://doardigital.tk
@token=eyJjb2RlIjoiYWRtXzYyNWViY2JkNWFkYjcifQ==.31ff8c14441f6bd1bf68836cf901ceba675fc350
@instituicao_fk=inst_628ea77b60f3c
@nome=Bruno Ap.
@cpf=548.315.690-03
@sexo=MASCULINO
@telefone=(82) 9 9977-6698
@email=br.rafael@outlook.com
@cep=06786-270
@logadouro=Rua das Capivaras
@complemento=
@numero=105 A
@bairro=JD Margarida
@cidade=Taboão da serra
@estado=SP
@valor=41.4
@recorrente=0
@tipo_pagamento=BOLETO
@card_nome=Bruno Ap Vieira
@card_numero=5119 4054 5033 2489
@card_validade=05/2023
@card_cvv=159

###
GET {{host}}/api/fatura

###
POST {{host}}/api/fatura/create
Content-Type: application/x-www-form-urlencoded;

instituicao_fk={{instituicao_fk}}
&nome={{nome}}
&cpf={{cpf}}
&sexo={{sexo}}
&telefone={{telefone}}
&email={{email}}
&cep={{cep}}
&logadouro={{logadouro}}
&complemento={{complemento}}
&numero={{numero}}
&bairro={{bairro}}
&cidade={{cidade}}
&estado={{estado}}
&valor={{valor}}
&recorrente={{recorrente}}
&tipo_pagamento={{tipo_pagamento}}
&card_nome={{card_nome}}
&card_numero={{card_numero}}
&card_validade={{card_validade}}
&card_cvv={{card_cvv}}
