@host=https://hostdoar.tk
@data_inicio=2022-07-01
@data_fim=2022-08-05
@status=PENDING
@institution_fk=
@save=0

###
GET {{host}}/api/fix-mensage.php?data_inicio={{data_inicio}}&data_fim={{data_fim}}&status={{status}}&institution_fk={{institution_fk}}&save={{save}}
