@host=http://doardigital.con
@data_inicio=2022-05-1
@data_fim=2022-09-1
@status=OVERDUE
@institution_fk=inst_62d990c744f00
@save=0

###
GET {{host}}/api/fix-mensage.php?data_inicio={{data_inicio}}&data_fim={{data_fim}}&status={{status}}&institution_fk={{institution_fk}}&save={{save}}
