@host=https://hostdoar.tk
@token=eyJjb2RlIjoiYWRtXzYyYTFmOGUzNTI4ZWUifQ==.7653c77bff2b2c012545f7ec98df4a0ae7f39df7
@institution_fk=inst_62d990c744f00
@nome=Bruno Ap. Vieira
@cpfCnpj=673.904.610-71
@email=br.rafael18@outlook.com
@telefone=(11) 94949-9944
@domain=teste.hostdoar.tk
@subdomain=teste.hostdoar.tk
@logo=logo.png
@icon=logo.png
@cor=#C00
@titulo=BETA
@tags=Site,Doação
@descricao=site para arrecadar doação
@tipoEmpresa=MEI
@cep=06786-270
@logradouro=Rua das capivaras
@numero=105-AB
@complemento=casa
@bairro=JD Margaridas
@cidade=Taboão da serra
@estado=SP
@adm_fk=sub_62d01a71a2b1a
@account=54799
@accountDigit=5
@accountName=Itaú
@agency=9313
@bank=341
@bankAccountType=CONTA_CORRENTE
@action=0
@valor=22,50
@payment_id=pay_4638472230001948


###
GET {{host}}/api/instituicao

###
POST {{host}}/api/instituicao/register
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&nome={{nome}}
&cpfCnpj={{cpfCnpj}}
&email={{email}}
&telefone={{telefone}}
&subdomain={{subdomain}}
&tipoEmpresa={{tipoEmpresa}}
&cep={{cep}}
&logradouro={{logradouro}}
&numero={{numero}}
&complemento={{complemento}}
&bairro={{bairro}}
&cidade={{cidade}}
&estado={{estado}}
&adm_fk={{adm_fk}}
&account={{account}}
&accountDigit={{accountDigit}}
&accountName={{accountName}}
&agency={{agency}}
&bank={{bank}}
&bankAccountType={{bankAccountType}}
&debug=0

###
GET {{host}}/api/instituicao/list?token={{token}}&adm_fk={{adm_fk}}

###
GET {{host}}/api/instituicao/info?domain={{domain}}

###
POST {{host}}/api/instituicao/update-info
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&institution_fk={{institution_fk}}
&nome={{nome}}
&email={{email}}
&telefone={{telefone}}
&domain={{domain}}
&logo={{logo}}
&icon={{icon}}
&cor={{cor}}
&titulo={{titulo}}
&tags={{tags}}
&descricao={{descricao}}
&cep={{cep}}
&logradouro={{logradouro}}
&numero={{numero}}
&complemento={{complemento}}
&bairro={{bairro}}
&cidade={{cidade}}
&estado={{estado}}


###
GET {{host}}/api/instituicao/balance?token={{token}}&institution_fk={{institution_fk}}&debug=1

###
GET {{host}}/api/instituicao/donation?token={{token}}&institution_fk={{institution_fk}}

###
POST {{host}}/api/instituicao/set-adm
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&institution_fk={{institution_fk}}
&adm_fk={{adm_fk}}
&action={{action}}

###
POST {{host}}/api/instituicao/saque
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&institution_fk={{institution_fk}}
&valor={{valor}}

###
POST {{host}}/api/instituicao/subscription-cancel
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&institution_fk=inst_62d990c744f00
&sub_fk=sub_figg9YEedPAk

###
GET {{host}}/api/instituicao/validar-envio?payment_id={{payment_id}}&debug=1

###
GET {{host}}/api/instituicao/resgata-status-fatura?payment_id={{payment_id}}

###
GET {{host}}/api/instituicao/re-tentativa?payment_id={{payment_id}}