@host=https://doardigital.tk
@token=eyJjb2RlIjoiYWRtXzYyNWViY2JkNWFkYjcifQ==.31ff8c14441f6bd1bf68836cf901ceba675fc350
@institution_fk=inst_628cd9db47cdc
@nome=Bruno Ap. Vieira
@cpfCnpj=673.904.610-71
@email=br.rafael11@outlook.com
@telefone=(11) 94949-9944
@domain=rafael11.doardigital.con
@subdomain=rafael11.doardigital.con
@logo=logo.png
@icon=logo.png
@cor=#C00
@titulo=BETA
@tags=Site,Doação
@descricao=site para arrecadar doação
@tipoEmpresa=MEI
@cep=06786-270
@logradouro=Rua das capivaras
@numero=105-AB
@complemento=casa
@bairro=JD Margaridas
@cidade=Taboão da serra
@estado=SP
@adm_fk=adm_007
@account=54799
@accountDigit=5
@accountName=Itaú
@agency=9313
@bank=341
@bankAccountType=CONTA_CORRENTE

##
GET {{host}}/api/instituicao

###
POST {{host}}/api/instituicao/register
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&nome={{nome}}
&cpfCnpj={{cpfCnpj}}
&email={{email}}
&telefone={{telefone}}
&subdomain={{subdomain}}
&tipoEmpresa={{tipoEmpresa}}
&cep={{cep}}
&logradouro={{logradouro}}
&numero={{numero}}
&complemento={{complemento}}
&bairro={{bairro}}
&cidade={{cidade}}
&estado={{estado}}
&adm_fk={{adm_fk}}
&account={{account}}
&accountDigit={{accountDigit}}
&accountName={{accountName}}
&agency={{agency}}
&bank={{bank}}
&bankAccountType={{bankAccountType}}
# &debug=1


###
GET {{host}}/api/instituicao/list?token={{token}}&adm_fk={{adm_fk}}

###
GET {{host}}/api/instituicao/info?domain={{domain}}&token={{token}}

###
POST {{host}}/api/instituicao/update-info
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&institution_fk={{institution_fk}}
&nome={{nome}}
&email={{email}}
&telefone={{telefone}}
&domain={{domain}}
&logo={{logo}}
&icon={{icon}}
&cor={{cor}}
&titulo={{titulo}}
&tags={{tags}}
&descricao={{descricao}}
&cep={{cep}}
&logradouro={{logradouro}}
&numero={{numero}}
&complemento={{complemento}}
&bairro={{bairro}}
&cidade={{cidade}}
&estado={{estado}}


###
GET {{host}}/api/instituicao/balance?token={{token}}&institution_fk={{institution_fk}}

###
GET {{host}}/api/instituicao/donation?token={{token}}&institution_fk={{institution_fk}}
