@host=https://hostdoar.tk

@protocolo=rec_e770a70ad0862ba7c0909cff553d0eae0f227ed4
@email=br.rafael@outlook.com
@valor=10
@recorrente=0
@nome=Bruno Vieira
@telefone=(11) 9 4949-9944
@cpf=962.250.040-41
@tipo_pagamento=PIX
@institution_fk=inst_62d98175c7e51

###
GET {{host}}/api/recover/

###
POST {{host}}/api/recover/save
Content-Type: application/x-www-form-urlencoded;

institution_fk={{institution_fk}}
&email={{email}}
&valor={{valor}}
&recorrente={{recorrente}}

###
POST {{host}}/api/recover/save
Content-Type: application/x-www-form-urlencoded;

institution_fk={{institution_fk}}
&email={{email}}
&valor={{valor}}
&recorrente={{recorrente}}
&protocolo={{protocolo}}
&nome={{nome}}
&telefone={{telefone}}
&cpf={{cpf}}
&tipo_pagamento={{tipo_pagamento}}

###
POST {{host}}/api/recover/finalizar
Content-Type: application/x-www-form-urlencoded;

protocolo={{protocolo}}

###
POST {{host}}/api/recover/info
Content-Type: application/x-www-form-urlencoded;

protocolo={{protocolo}}

