@host=http://hostdoar.tk
# @host=http://localhost/v2-doardigital

###

POST {{host}}/api/webhook.php
content-type: application/json

{
    "event": "PAYMENT_CREATED",
    "payment": {
        "object": "payment",
        "id": "pay_7413770397583471",
        "dateCreated": "2023-01-05",
        "customer": "cus_000004878952",
        "subscription": "sub_SboYJQeaNiZS",
        "paymentLink": null,
        "value": 45.30,
        "netValue": 43.31,
        "originalValue": null,
        "interestValue": null,
        "description": "Assinatura",
        "billingType": "PIX",
        "pixTransaction": null,
        "status": "PENDING",
        "dueDate": "2023-02-13",
        "originalDueDate": "2023-02-13",
        "paymentDate": null,
        "clientPaymentDate": null,
        "installmentNumber": null,
        "invoiceUrl": "https://sandbox.asaas.com/i/7413770397583471",
        "invoiceNumber": "01708400",
        "externalReference": "ref_62a744d274b1f",
        "deleted": false,
        "anticipated": false,
        "anticipable": false,
        "creditDate": null,
        "estimatedCreditDate": null,
        "transactionReceiptUrl": null,
        "nossoNumero": null,
        "bankSlipUrl": null,
        "lastInvoiceViewedDate": null,
        "lastBankSlipViewedDate": null,
        "discount": {
            "value": 0.00,
            "limitDate": null,
            "dueDateLimitDays": 0,
            "type": "FIXED"
        },
        "fine": {
            "value": 0.00,
            "type": "FIXED"
        },
        "interest": {
            "value": 0.00,
            "type": "PERCENTAGE"
        },
        "postalService": false,
        "refunds": null
    }
}