@host=https://hostdoar.tk

###

POST {{host}}/api/webhook.php
content-type: application/json

{
    "event": "PAYMENT_UPDATED",
    "payment": {
        "object": "payment",
        "id": "pay_5043535382700573",
        "dateCreated": "2022-11-21",
        "customer": "cus_000043039152",
        "paymentLink": null,
        "value": 10,
        "netValue": 9.2200000000000006394884621840901672840118408203125,
        "originalValue": null,
        "interestValue": null,
        "description": "Doa\u00e7\u00e3o Unica",
        "billingType": "CREDIT_CARD",
        "confirmedDate": "2022-11-21",
        "creditCard": {
            "creditCardNumber": "1905",
            "creditCardBrand": "AMEX"
        },
        "pixTransaction": null,
        "status": "PENDING",
        "dueDate": "2022-11-21",
        "originalDueDate": "2022-11-21",
        "paymentDate": null,
        "clientPaymentDate": "2022-11-21",
        "installmentNumber": null,
        "invoiceUrl": "https:\/\/www.asaas.com\/i\/1060467724156351",
        "invoiceNumber": "156630437",
        "externalReference": "ref_637bc911b718f",
        "deleted": false,
        "anticipated": false,
        "anticipable": false,
        "creditDate": null,
        "estimatedCreditDate": "2022-12-21",
        "transactionReceiptUrl": "https:\/\/www.asaas.com\/comprovantes\/9002501108376010",
        "nossoNumero": null,
        "bankSlipUrl": null,
        "lastInvoiceViewedDate": null,
        "lastBankSlipViewedDate": null,
        "split": [
            {
                "id": "76e356e1-c062-4275-b5fe-e388f5b9c0ee",
                "walletId": "628c021e-0220-403a-8e67-34716ee5ecf6",
                "fixedValue": null,
                "percentualValue": 4,
                "totalValue": 0.35999999999999998667732370449812151491641998291015625
            }
        ],
        "postalService": false,
        "refunds": null
    }
}