@host=http://hostdoar.tk
@token=eyJjb2RlIjoiYWRtXzYyNWViY2JkNWFkYjcifQ==.31ff8c14441f6bd1bf68836cf901ceba675fc350
@instituicao_fk=inst_62d990c744f00
@tipo=PIX
@status_pagamento=CONFIRMED
@content=KKKKK

###
GET {{host}}/api/whats-template

###
GET {{host}}/api/whats-template/info?token={{token}}&tipo={{tipo}}&status_pagamento={{status_pagamento}}&instituicao_fk={{instituicao_fk}}

###
GET {{host}}/api/whats-template/list?token={{token}}&instituicao_fk={{instituicao_fk}}

###
POST {{host}}/api/whats-template/save
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&tipo={{tipo}}
&instituicao_fk={{instituicao_fk}}
&status_pagamento={{status_pagamento}}
&content={{content}}

###
POST {{host}}/api/whats-template/recover
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&tipo={{tipo}}
&status_pagamento={{status_pagamento}}
&instituicao_fk={{instituicao_fk}}

###
POST {{host}}/api/whats-template/install
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&instituicao_fk={{instituicao_fk}}

###
POST {{host}}/api/whats-template/reset
Content-Type: application/x-www-form-urlencoded;

token={{token}}
&instituicao_fk={{instituicao_fk}}