export default [
  { text: "Inicio", ico: "fa-solid fa-house-flag", link: "dashboard" },
  { text: "Doadores", ico: "fa-solid fa-user-group", link: "doadores" },
  { text: "Doações", ico: "fa-solid fa-hand-holding-dollar", link: "doacoes" },
  { text: "Lançamentos", ico: "fa-solid fa-credit-card", link: "recorrencia" },
  { text: "Planos", ico: "fa-solid fa-clipboard-list", link: "planos" },
  { text: "Metas", ico: "fa-solid fa-chart-line", link: "metas" },
  { text: "Módulos", ico: "fa-solid fa-share-nodes", link: "modulos" },
  { text: "Modelo de E-mails", ico: "fa-solid fa-envelope-circle-check", link: "modelo-de-email" },
  { text: "Configuração", ico: "fa-solid fa-gear", link: "configuracao" },
  { text: "Usuários", ico: "fas fa-user-edit", link: "usuarios" },
  { text: "Minhas Instituições", ico: "fa-solid fa-house-laptop", link: "minhas-instituicoes" },
  { text: "Carteira", ico: "fa-solid fa-vault", link: "carteira" },
  { text: "QR CODE", ico: "fa-solid fa-qrcode", link: "qr-code" },
]