
POST https://doardigital.tk/api/completar-profile
Content-Type: Content-Type: application/x-www-form-urlencoded

token=string
&cpf_cnpj=string
&data_nascimento=string
&tipo=string

###
POST https://doardigital.tk/api/update-endereco
Content-Type: Content-Type: application/x-www-form-urlencoded

token=string
&nome_identificacao=string
&cep=string
&logradouro=string
&numero=string
&complemento=string
&bairro=string
&cidade=string
&estado=string

###
POST https://doardigital.tk/api/recorrencia-digital
Content-Type: Content-Type: application/x-www-form-urlencoded

token=string
&plano_token=string
&amount=int
&cart_nome=string
&cart_numero=string
&cart_cvv=int
&cart_validade=string