


POST https://doardigital.com.br/api/recorrencia-digital
Content-Type: Content-Type: application/x-www-form-urlencoded

token=string
&plano_token=string
&amount=int
&cart_nome=string
&cart_numero=string
&cart_cvv=int
&cart_validade=string