###
GET https://doardigital.com.br/api/instituicao?token=eyJzZWNyZXQiOiI2MjEzY2FkNmFiYzgzIiwibm9tZSI6IlZJQ1RPUiBGRVJOQU5ETyBNQUdBTEhBRVMgVkFTQ09OQ0VMT1MiLCJlbWFpbCI6InZpY3RvcmZlcm5hbmRvbWFnQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.c5a908ab74f3a6ed8329ef179d4c00e0f4b3f280
Content-Type: application/x-www-form-urlencoded


POST https://doardigital.com.br/api/create-instituicao
Content-Type: application/x-www-form-urlencoded

token=eyJzZWNyZXQiOiI2MjEzY2FkNmFiYzgzIiwibm9tZSI6IlZJQ1RPUiBGRVJOQU5ETyBNQUdBTEhBRVMgVkFTQ09OQ0VMT1MiLCJlbWFpbCI6InZpY3RvcmZlcm5hbmRvbWFnQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.c5a908ab74f3a6ed8329ef179d4c00e0f4b3f280
&nome_fantasia=GilMinas
&razao_social=minas
&subdomaim=gilminas.gm
&email=gilminas@gmail.com
&cnpj=123.456.789-31
&telefone=(38) 998019-210

###

GET https://doardigital.com.br/api/subdominio-disponivel?subdomaim=gilminas.gm&token=eyJzZWNyZXQiOiI2MjEzY2FkNmFiYzgzIiwibm9tZSI6IlZJQ1RPUiBGRVJOQU5ETyBNQUdBTEhBRVMgVkFTQ09OQ0VMT1MiLCJlbWFpbCI6InZpY3RvcmZlcm5hbmRvbWFnQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.c5a908ab74f3a6ed8329ef179d4c00e0f4b3f280
Content-Type: application/x-www-form-urlencoded

###
GET https://doardigital.com.br/api/info-subdomaim?subdomaim=gilminas.gm&token=eyJzZWNyZXQiOiI2MjEzY2FkNmFiYzgzIiwibm9tZSI6IlZJQ1RPUiBGRVJOQU5ETyBNQUdBTEhBRVMgVkFTQ09OQ0VMT1MiLCJlbWFpbCI6InZpY3RvcmZlcm5hbmRvbWFnQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.c5a908ab74f3a6ed8329ef179d4c00e0f4b3f280
Content-Type: application/x-www-form-urlencoded

###

POST https://doardigital.com.br/api/endereco-instituicao
Content-Type: application/x-www-form-urlencoded

token=eyJzZWNyZXQiOiI2MjEzY2FkNmFiYzgzIiwibm9tZSI6IlZJQ1RPUiBGRVJOQU5ETyBNQUdBTEhBRVMgVkFTQ09OQ0VMT1MiLCJlbWFpbCI6InZpY3RvcmZlcm5hbmRvbWFnQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.c5a908ab74f3a6ed8329ef179d4c00e0f4b3f280
&id=132
&nome_identificacao=instituicao
&logradouro=Rua Plínio Rocha Pinto
&complemento=casa
&bairro=Vila Serralheiro
&cidade=São Paulo
&estado=SP
&numero=76
&cep=02835090

###

POST https://doardigital.com.br/api/create-conta-instituicao
Content-Type: application/x-www-form-urlencoded

token=string
&instituicao_id=id
&codigo_banco=string
&agencia=string
&conta=string
&conta_digito=string
&tipo_conta=string
&nome_completo=string
&documento_numero=string
&recebedor_nome=string
&email_recebedor=string
&cnpj=string
&site_url=string
&telefone_recebedor=string


###

POST https://doardigital.com.br/api/on-off-instituicao
Content-Type: application/x-www-form-urlencoded

token=eyJzZWNyZXQiOiI2MjEzY2FkNmFiYzgzIiwibm9tZSI6IlZJQ1RPUiBGRVJOQU5ETyBNQUdBTEhBRVMgVkFTQ09OQ0VMT1MiLCJlbWFpbCI6InZpY3RvcmZlcm5hbmRvbWFnQGdtYWlsLmNvbSIsInN1cGVyX2FkbSI6IjAiLCJzdGVwIjoiMSJ9.c5a908ab74f3a6ed8329ef179d4c00e0f4b3f280
&instituicao_id=int

###
