GET https://doardigital.tk/api/instituicao?token=string
Content-Type: application/x-www-form-urlencoded

###
GET https://doardigital.tk/api/list-credencial?token=string
Content-Type: application/x-www-form-urlencoded

###
POST https://doardigital.tk/api/criate-subadm
Content-Type: application/x-www-form-urlencoded

token=string
&nome=string
&email=string
&senha=string
&telefone=string
&credencial_id=int


###
GET https://doardigital.tk/api/list-subadm?token=string
Content-Type: application/x-www-form-urlencoded
